---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a k8s repository file
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding the repo details in k8s repo config file
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing Docker and firewalld
    shell: |
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y --nobest
     yum install firewalld -y
     yum install -y yum-utils device-mapper-persistent-data lvm2

  - name: Installing required packages
    yum:
     name: "{{ item }}"
     state: present
    with_items: "{{ packages }}"

  - name: Starting and enabling the services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow ports om firewall demon
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Enabling firewall bridge rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
