---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a k8s repository file
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding the repo details in k8s repo config file
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Add docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Installing docker package
    shell: yum install -y docker-ce --nobest

  - name: Installing required pip packages
    pip:
      name: "{{ pip_packages }}"

  - name: Starting and enabling the services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow ports in firewall daemon
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Add IP address of all known nodes to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: Enabling firewall bridge rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

  - name: Enabling permanent firewall masquerade and public zone
    firewalld:
      zone: public
      state: enabled
      masquerade: yes
      permanent: yes

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Enabling cluster addresses in firewall
    firewalld:
      zone: public
      state: enabled
      permanent: yes
      rich_rule: rule family=ipv4 source address="{{ cidr_v }}" accept

  - name: Reload the firewall rules
    shell: firewall-cmd --reload

  - name: Set sysctl rules
    sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
    with_items: "{{ sysctl }}"

  - name: Reload sysctl rules
    shell: sysctl --system
