---
- hosts: kubernetes-worker-nodes
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
  - env_variables

  pre_tasks:
  - name: Wait for play hosts to be up again
    wait_for:
      host: '{{hostvars[item].ansible_host}}'
      port: 22
      state: started
      delay: 10
      timeout: 45
    with_items: '{{play_hosts}}' 
    connection: local
  - setup:

  tasks:
  - name: Copying security token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker node with k8s master
    shell: |
     kubeadm reset -f
     cat join_token | tail -2 > out.sh
     sh out.sh
