---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling swap on the node
    shell: swapoff -a

  - name: Disabling the swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  
