---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Nexus app
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: bitbucket
          name: bitbucket
          namespace: dev-tools
        spec:
          selector:
            matchLabels:
              app: bitbucket
          replicas: 1
          template:
            metadata:
              labels:
                app: bitbucket
              name: bitbucket
            spec:
              containers:
                - name: bitbucket
                  image: "atlassian/bitbucket-server"
                  resources:
                    requests:
                      memory: "2G"
                  volumeMounts:
                    - name: "bitbucket-pv-volume"
                      mountPath: /var/atlassian/application-data/bitbucket
              volumes:
                - name: "bitbucket-pv-volume"
                  persistentVolumeClaim:
                    claimName: bitbucket-pv-claim
