apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/confluence-home"

