---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jenkins service
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jenkins-service
          namespace: dev-tools
          annotations:
        spec:
          selector: 
            app: jenkins
          type: NodePort  
          ports:
          - port: 8081
            targetPort: 8081
            nodePort: 42000
