---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jenkins NodePort Service
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jenkins-service
          namespace: dev-tools
        spec:
          selector: 
            app: jenkins
          type: NodePort  
          ports:
          - port: 8080
            targetPort: 8080
            nodePort: 32100
