---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jenkins App
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: jenkins
          namespace: dev-tools
        spec:
          selector:
            matchLabels:
              app: jenkins
          replicas: 1
          template:
            metadata:
              labels:
                app: jenkins
              name: jenkins
            spec:
              securityContext:
                fsGroup: 1000 
                runAsUser: 0
              containers:
                - name: jenkins
                  image: jenkins/jenkins:lts
                  resources:
                    requests:
                      memory: "2G"
                  volumeMounts:
                    - name: jenkins-pv-volume
                      mountPath: /var/jenkins_home
                  ports:
                    - containerPort: 8080
              volumes:
                - name: jenkins-pv-volume
                  persistentVolumeClaim:
                    claimName: jenkins-pv-claim
