---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jenkins Service
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jenkins-service
          namespace: dev-tools
          annotations:
            prometheus.io/scrape: 'true'
            prometheus.io/path:   /
            prometheus.io/port:   '8080'
        spec:
          selector: 
            app: jenkins
          type: NodePort  
          ports:
          - port: 8080
            targetPort: 8080
            nodePort: 32100
