---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a Jira service
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: jira-service
          namespace: dev-tools
          annotations:
        spec:
          selector: 
            app: jira
          type: NodePort  
          ports:
          - port: 8081
            targetPort: 8081
            nodePort: 82000
