---
- hosts: kubernetes-slave-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Create a PVC for the Nexus App
    k8s:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nexus-pv-claim
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
