---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Create a PVC for the Nexus App
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: nexus-pv-claim
          namespace: dev-tools
        spec:
          storageClassName: manual
          accessModes:
            - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
